### ISSUE TITLE
모바일 apk파일 다운로드

### ISSUE THREAD

**Issue by ananjaemin** [tempfiles-team/tempfiles-backend#32]
zip파일로 변형되고 핸드폰에선 압축해제하고 나면 앱 다운로드가 안됩니다.

**Comment by minpeter** [comment]
ㅖ 해결됬네요

https://vercel.tmpf.me

**Comment by minpeter** [comment]
확인해보시죠

**Comment by minpeter** [comment]
아마도 id에 파일 하나였을떄 생기는 문제, 현재는 folder / file 시스템이 생겨서 자동적으로 해결된 듯함
